fail_fast: false
default_language_version:
    python: python3
default_stages:
-   commit
-   push
minimum_pre_commit_version: 2.9.3
repos:
-   repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
    -   id: black
        additional_dependencies: [toml]
        args: [--line-length=88, --experimental-string-processing]
-   repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
    -   id: isort
        additional_dependencies: [toml]
        args: [--order-by-type, --profile, 'black']
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: detect-private-key
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: check-symlinks
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: fix-encoding-pragma
        args: [--remove]
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: trailing-whitespace
        exclude: ^.bumpversion.cfg$
    -   id: check-case-conflict
    -   id: check-docstring-first
    # -   id: check-yaml
    -   id: check-toml
    -   id: requirements-txt-fixer
-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
    -   id: script-must-have-extension
        name: Check executable files use .sh extension
        types: [shell, executable]
-   repo: https://github.com/myint/rstcheck
    rev: 3f92957478422df87bd730abde66f089cc1ee19b
    hooks:
    -   id: rstcheck
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==20.8b1]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.10.1
    hooks:
    -   id: pyupgrade
        args: [--py3-plus, --py37-plus]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.8.0
    hooks:
    -   id: python-no-eval
    -   id: python-use-type-annotations
    # -   id: python-check-blanket-noqa
    -   id: rst-backticks
    -   id: rst-directive-colons
    -   id: rst-inline-touching-normal
-   repo: https://github.com/PyCQA/doc8
    rev: 0.9.0a1
    hooks:
    -   id: doc8
        args: [--max-line-length=88]
# -   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
#     rev: v2.0.0
#     hooks:
#     -   id: pretty-format-yaml
#         args: [--autofix, --indent, '4']
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-tidy-imports, flake8-docstrings, flake8-comprehensions, flake8-bugbear, flake8-blind-except]
        args: [--max-line-length=88, --config=setup.cfg]
-   repo: https://github.com/asottile/yesqa
    rev: v1.2.2
    hooks:
    -   id: yesqa
        additional_dependencies: [flake8-tidy-imports, flake8-docstrings, flake8-comprehensions, flake8-bugbear, flake8-blind-except]
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.800
#     hooks:
#     -   id: mypy
#         additional_dependencies: [numpy, scipy, pandas]
